# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Periodic Table
email: bmcgui7575@greenvilleschools.us
description: > # this means to ignore newlines until "baseurl:"
  A digital representation of a periodic table, made for Mr. Ginn's 4th Period NT Chemistry Class
baseurl: "/periodic-table/" # the subpath of your site, e.g. /blog
url: "https://mayormonty.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


data_dir: data